version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: formfortress_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - formfortress_net

networks:
  formfortress_net:
    driver: bridge
